export { User, IUser } from "./User";
export { School, ISchool } from "./School";
export { Subscription, ISubscription } from "./Subscription";
export { Plan, IPlan } from "./Plan";
export { Diploma, IDiploma } from "./Diploma";
export { TemplateDiploma, ITemplateDiploma } from "./TemplateDiploma";
export { Training, ITraining } from "./Training";
export { Student, IStudent } from "./Student";
export { Speciality, ISpeciality } from "./Speciality";
